version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: sass-rails
    versions:
    - 6.0.0
  - dependency-name: puma
    versions:
    - 3.12.6
    - 5.2.2
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: rails-html-sanitizer
    versions:
    - 1.3.0
